version: '3.5'

services:

  php:
    image: easyengine/php:v4.5.4
    restart: always
    labels:
      - "io.easyengine.site=${VIRTUAL_HOST}"
    volumes:
      - "htdocs:/var/www"
      - "config_php:/usr/local/etc"
      - "log_php:/var/log/php"
      - "newrelic_sock:/run/newrelic"
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - USER_ID
      - GROUP_ID
      - VIRTUAL_HOST
      - NEWRELIC_APPNAME=${VIRTUAL_HOST}
      - NEWRELIC_LICENSE_KEY
    external_links:
      - services_global-nginx-proxy_1:${VIRTUAL_HOST}
    networks:
      site-network:
        aliases:
          - ${VIRTUAL_HOST}_php
      global-backend-network:

  nginx:
    image: easyengine/nginx:v4.5.4
    depends_on:
      - php
    restart: always
    labels:
      - "io.easyengine.site=${VIRTUAL_HOST}"
    volumes:
      - "htdocs:/var/www"
      - "config_nginx:/usr/local/openresty/nginx/conf"
      - "log_nginx:/var/log/nginx"
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PATH=/
      - HSTS=off
      - HTTPS_METHOD=nohttps
    external_links:
      - services_global-nginx-proxy_1:${VIRTUAL_HOST}
    networks:
      global-frontend-network:
      site-network:
      global-backend-network:

  mailhog:
    image: easyengine/mailhog:v4.0.0
    restart: always
    command: ["-invite-jim=false"]
    labels:
      - "io.easyengine.site=${VIRTUAL_HOST}"
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PATH=/ee-admin/mailhog/
      - VIRTUAL_PORT=8025
    external_links:
      - services_global-nginx-proxy_1:${VIRTUAL_HOST}
    networks:
      site-network:
      global-frontend-network:

  postfix:
    image: easyengine/postfix:v4.1.5
    hostname: ${VIRTUAL_HOST}
    restart: always
    labels:
      - "io.easyengine.site=${VIRTUAL_HOST}"
    volumes:
      - "/dev/log:/dev/log"
      - "data_postfix:/var/spool/postfix"
      - "ssl_postfix:/etc/ssl/postfix"
      - "config_postfix:/etc/postfix"
    external_links:
      - services_global-nginx-proxy_1:${VIRTUAL_HOST}
    networks:
      site-network:


volumes:
  htdocs:
    external:
      name: duyphambiz_htdocs
  config_nginx:
    external:
      name: duyphambiz_config_nginx
  config_php:
    external:
      name: duyphambiz_config_php
  log_php:
    external:
      name: duyphambiz_log_php
  log_nginx:
    external:
      name: duyphambiz_log_nginx
  data_postfix:
    external:
      name: duyphambiz_data_postfix
  ssl_postfix:
    external:
      name: duyphambiz_ssl_postfix
  config_postfix:
    external:
      name: duyphambiz_config_postfix
  newrelic_sock:
    external:
      name: global-newrelic-daemon_newrelic_sock

networks:
  site-network:
    name: ${VIRTUAL_HOST}
    labels:
     - "org.label-schema.vendor=EasyEngine"
     - "io.easyengine.site=${VIRTUAL_HOST}"
  global-frontend-network:
    external:
      name: ee-global-frontend-network
  global-backend-network:
    external:
      name: ee-global-backend-network
